# Generated by Django 5.1.2 on 2025-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('packet_size', models.FloatField()),
                ('packet_rate', models.FloatField()),
                ('connection_duration', models.FloatField()),
                ('protocol', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('anomaly_score', models.FloatField()),
                ('prediction', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
